# fly.toml app configuration file generated for trackr-prod on 2023-10-12T16:56:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "trackr-prod"
primary_region = "ams"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
